#!/bin/bash -l

#SBATCH --job-name=priorfit
#SBATCH --account=OD-228777
#SBATCH --array=0-279%200
#SBATCH --time=19:59:00
#SBATCH --ntasks=1
#SBATCH --mem=5gb
#SBATCH --output=logs/priorfit/priorfit_TASK%a_JOB%A.out
#SBATCH --error=logs/priorfit/priorfit_TASK%a_JOB%A.err
#SBATCH --mail-type=end # send email when job ends
#SBATCH --mail-user=julien.lerat@csiro.au

# ----- VARIABLES TO SET ----------
# VERSION: e.g. 1
#

#set -xv
conda activate env_jl_v1_pet

echo --- System info ---
echo whoami  : `whoami`
echo date    : `date -u`
echo hostname: `hostname -f`
echo uname   : `uname -a`
echo issue   : `cat /etc/issue`
echo release : `lsb_release -a` 
echo python  : `which python`

BASE=PR002_compute_priors
PYSCRIPT=$NFCVP/scripts/priors/$BASE.py
FLOG=$NFCVP/logs/priorfit

## WARNING !
## Don't forget to export ALL as well otherwise the script won't load the
## the python env
## e.g. sbatch --export=ALL,VERSION=1 calmodel.job

# Extract IDs
jobid=$SLURM_ARRAY_JOB_ID
taskid=$SLURM_ARRAY_TASK_ID

# Run job
echo
echo --- Job info ---

ferr=$FLOG/priorfit_TASK${taskid}_JOB${jobid}.err
echo "Running task " $taskid
python $PYSCRIPT -t $taskid  -v $VERSION

